wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 128
epochs:
  value: 50
l_hidden:
  value: 150
l_input:
  value: 784
l_output:
  value: 10
learning_rate:
  value: 0.09969187236420944
loss:
  value: CrossEntropy
nesterov:
  value: true
optimizer:
  value: SGD
val_batch_size:
  value: 500
