wandb_version: 1

program:
  desc: null
  value: training.py
method:
  desc: null
  value: random
name:
  desc: null
  value: sweep
metric:
  desc: null
  value:
    goal: maximize
    name: acc_val
parameters:
  desc: null
  value:
    epochs:
      value: 20
    l_input:
      value: 784
    l_hidden:
      value: 100
    l_output:
      value: 10
    learning_rate:
      value: 0.01
    optimizer:
      value: SGD_SAM
    loss:
      value: CrossEntropy
    batch_size:
      value: 256
    val_batch_size:
      value: 500
    activation:
      value: ReLU
    nesterov:
      value: true
    momentum:
      value: 0.9
_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699902654.220437
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.11.6
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
