wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 64
epochs:
  value: 50
l_hidden:
  value: 100
l_input:
  value: 784
l_output:
  value: 10
learning_rate:
  value: 0.026714394863026143
loss:
  value: CrossEntropy
optimizer:
  value: SGD
val_batch_size:
  value: 500
