wandb_version: 1

activation:
  value: RMSProp
batch_size:
  value: 256
epochs:
  value: 50
l_hidden:
  value: 50
l_input:
  value: 784
l_output:
  value: 10
learning_rate:
  value: 0.08893937625640226
loss:
  value: CrossEntropy
momentum:
  value: 0.9
nesterov:
  value: true
optimizer:
  value: Adam
val_batch_size:
  value: 500
