wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 64
epochs:
  value: 30
l_hidden:
  value: 100
l_input:
  value: 784
l_output:
  value: 10
learning_rate:
  value: 0.01
loss:
  value: CrossEntropy
momentum:
  value: 0.9
nesterov:
  value: true
optimizer:
  value: AdaGrad
val_batch_size:
  value: 500
