wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 128
epochs:
  value: 50
l_hidden:
  value: 50
l_input:
  value: 784
l_output:
  value: 10
learning_rate:
  value: 0.04805642647396555
loss:
  value: CrossEntropy
momentum:
  value: 0.9
nesterov:
  value: true
optimizer:
  value: SGD
val_batch_size:
  value: 500
