wandb_version: 1

epochs:
  desc: null
  value: 50
l_input:
  desc: null
  value: 784
l_hidden:
  desc: null
  value: 150
l_output:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.01
optimizer:
  desc: null
  value: SGD
loss:
  desc: null
  value: CrossEntropy
batch_size:
  desc: null
  value: 256
val_batch_size:
  desc: null
  value: 500
activation:
  desc: null
  value: ReLU
nesterov:
  desc: null
  value: true
momentum:
  desc: null
  value: 0.9
_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699911254.245591
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      - 35
      4: 3.11.6
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
